# Generated by Django 5.0.7 on 2024-07-21 04:25

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(max_length=500, validators=[Petstagram.photos.validators.validate_file_size])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(max_length=30)),
                ('date_of_publication', models.DateTimeField(auto_now_add=True)),
                ('tagged_pets', models.ManyToManyField(blank=True, to='pets.pet')),
            ],
        ),
    ]
