# Generated by Django 5.0.7 on 2024-07-21 06:11

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles/photos', validators=[Petstagram.photos.validators.validate_file_size]),
        ),
    ]
