# Generated by Django 5.0.7 on 2024-07-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
